TaskMenagerV2/Pages/Account.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TaskMenagerV2.Pages.dbcontroll;
using TaskMenagerV2.Pages.Services;


namespace TaskMenagerV2.Pages
{
    public class AccountModel : PageModel
    {
        private readonly IUserService _userService;
        private readonly MyDbContext _dbContext;
        private readonly EmailService _emailService;

        public AccountModel(IUserService userService, MyDbContext dbContext, EmailService emailService)
        {
            _userService = userService;
            _dbContext = dbContext;
            _emailService = emailService;
        }

        //password
        [BindProperty]
        public User UserC { get; set; }

        public async Task<IActionResult> OnPostUpdatePasswordAsync(int userId)
        {
            var user = await _userService.GetUserByIdAsync(userId);
            if(UserC.Name != null)
            {
                user.Name = UserC.Name;
            }
            if(UserC.Password != null)
            {
                user.Password = UserC.Password;
            }
            if(UserC.Email != null)
            {
                await _emailService.SendEmailAsync(user.Email, "Account data changing!", "You have changed your email.");
                user.Email = UserC.Email;
                await _emailService.SendEmailAsync(user.Email, "Account data changing!", "This is now your email.");
            }
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("/Account");
        }


        //logout
        public async Task<IActionResult> OnPostLogoutAsync()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Account");
        }

        public async Task<IActionResult> OnPostDeleteAccountAsync(int userId)
        {
            var user = await _userService.GetUserByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            await _userService.DeleteUserAsync(userId);
            HttpContext.Session.Clear(); 
            return RedirectToPage("/Account");
        }

        //achivements
        public async Task<IActionResult> OnGetAsync()
        {
            if (HttpContext.Session.GetString("UserId") != null)
            {

                //achivements
                int userId = int.Parse(HttpContext.Session.GetString("UserId"));
                var user = await _userService.GetUserByIdAsync(userId);
                ViewData["User"] = user;

                var achievementsString = user.Achivements;
                var achievementsList = achievementsString.Split(',').Select(int.Parse).ToList();

                var tasks = _dbContext.Tasks.ToList();
                var projects = _dbContext.Projects.ToList();

                for (int i = 0; i < achievementsList.Count; i++)
                {
                    if (achievementsList[i] == 0)
                    {
                        switch (i + 1)
                        {
                            case 1:
                                foreach (var task in tasks.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))))
                                {
                                    if (task.Completion == 1 && task.DateOfCreation == DateTime.Today)
                                    {
                                        achievementsList[i] = 1;
                                        break;
                                    }
                                }
                                break;

                            case 2:
                                foreach (var task in tasks.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))))
                                {
                                    if (task.Completion == 1)
                                    {
                                        achievementsList[i] = 1;
                                        break;
                                    }
                                }
                                break;

                            case 3:
                                foreach (var project in projects.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))))
                                {
                                    if (project.ProjectId >= 0)
                                    {
                                        achievementsList[i] = 1;
                                        break;
                                    }
                                }
                                break;

                            case 4:
                                int counter = 0;
                                foreach (var task in tasks.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))))
                                {
                                    if (task.Completion == 1)
                                    {
                                        counter++;
                                    }
                                    if (counter >= 10)
                                    {
                                        achievementsList[i] = 1;
                                        break;
                                    }
                                }
                                break;

                            case 5:
                                counter = 0;
                                foreach (var task in tasks.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))))
                                {
                                    if (task.Completion == 1)
                                    {
                                        counter++;
                                    }
                                    if (counter >= 50)
                                    {
                                        achievementsList[i] = 1;
                                        break;
                                    }
                                }
                                break;

                            case 6:
                                counter = 0;
                                foreach (var task in tasks.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))))
                                {
                                    if (task.Completion == 1)
                                    {
                                        counter++;
                                    }
                                    if (counter >= 100)
                                    {
                                        achievementsList[i] = 1;
                                        break;
                                    }
                                }
                                break;

                            case 7:
                                counter = 0;
                                foreach (var project in projects.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))))
                                {
                                    if(project.Tasks != null)
                                    {
                                        foreach (var task in project.Tasks)
                                        {
                                            if (task.Completion == 1)
                                            {
                                                counter++;
                                            }
                                        }
                                        if (counter == project.Tasks.Count)
                                        {
                                            achievementsList[i] = 1;
                                            break;
                                        }
                                    }
                                }
                                break;

                            case 8:
                                foreach (var task in tasks.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))))
                                {
                                    if (task.DateOfCompletion < DateTime.Now)
                                    {
                                        achievementsList[i] = 1;
                                        break;
                                    }
                                }
                                break;

                            case 9:
                                counter = 0;
                                int counterP = 0;
                                foreach (var project in projects.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))))
                                {
                                    if (project.Tasks != null)
                                    {
                                        foreach (var task in project.Tasks)
                                        {
                                            if (task.Completion == 1)
                                            {
                                                counter++;
                                            }
                                        }
                                        if (counter == project.Tasks.Count)
                                        {
                                            counterP++;
                                        }
                                    }
                                }

                                if (counterP >= 10)
                                {
                                    achievementsList[i] = 1;
                                    break;
                                }
                                break;

                            case 10:

TaskMenagerV2/Pages/AddNew.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TaskMenager.Components.dbcontroll;

namespace TaskMenagerV2.Pages
{
    public class AddNewModel : PageModel
    {
        private readonly MyDbContext _dbContext;

        public AddNewModel(MyDbContext dbContext)
        {
            _dbContext = dbContext;
            newProject = new Project();
            newTask = new Tasks();
        }

        [BindProperty]
        public Project newProject { get; set; }

        [BindProperty]
        public Tasks newTask { get; set; }

        [BindProperty]
        public string Action { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        [HttpPost]
        public async Task<IActionResult> OnPostAsync()
        {
            Console.WriteLine($"Action: {Action}");
            //fix this
            //if (!ModelState.IsValid)
            //{
            //    Console.WriteLine("Model is not valid!");
            //    return Page();
            //}
            Console.WriteLine("Model valid");
            if (Action == "AddProject")
            {
                Console.WriteLine("Toggeled AddProject");
                Console.WriteLine($"Project: {newProject.Name}, {newProject.Description}");
                _dbContext.Projects.Add(newProject);
                await _dbContext.SaveChangesAsync();
            }
            else if (Action == "AddTask")
            {
                if (newTask.DateOfCompletion.Date < DateTime.Today)
                {
                    ModelState.AddModelError("newTask.DateOfCompletion", "Date is not valid");
                    return Page();
                }

                _dbContext.Tasks.Add(newTask);
                Console.WriteLine($"Task: {newTask.ProjectId}, {newTask.DateOfCreation}, {newTask.Description}");
                await _dbContext.SaveChangesAsync();
            }

            return RedirectToPage("Index");
        }
    }
}

TaskMenagerV2/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TaskMenager.Components.dbcontroll;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using TaskMenager.Components.services;

namespace TaskMenagerV2.Pages
{
    public class EditModel : PageModel
    {
        private readonly MyDbContext _dbContext;
        private readonly ProjectService _projectService;
        private readonly Taskservice _taskService;
        public EditModel(MyDbContext dbContext, ProjectService projectService, Taskservice Taskservice)
        {
            _dbContext = dbContext;
            _projectService = projectService;
            editProject = new Project();
            editTask = new Tasks();
            _taskService = Taskservice;
        }

        [BindProperty]
        public Project editProject { get; set; }

        [BindProperty]
        public Tasks editTask { get; set; }

        [BindProperty]
        public string Action { get; set; }

        public List<Project> Projects { get; set; }

        public IActionResult OnGet()
        {
            Projects = _dbContext.Projects.Include(p => p.Tasks).ToList();
            return Page();
        }

        [HttpPost]
        public async Task<IActionResult> OnPostAsync()
        {
            if (Action == "EditProject")
            {
                var project = await _dbContext.Projects.FindAsync(editProject.ProjectId);
                if (project != null)
                {
                    project.Name = editProject.Name;
                    project.Description = editProject.Description;
                    await _dbContext.SaveChangesAsync();
                }
            }
            else if (Action == "EditTask")
            {
                var task = await _dbContext.Tasks.FindAsync(editTask.Id);
                if (task != null)
                {
                    task.ProjectId = editTask.ProjectId;
                    task.Description = editTask.Description;
                    await _dbContext.SaveChangesAsync();
                }
            }
            else if (Action == "DeleteProject")
            {
                var projectD = await _dbContext.Projects.FindAsync(editProject.ProjectId);
                if (projectD != null)
                {
                    await _projectService.DeleteProjectAsync(projectD.ProjectId);
                }
            }
            else if (Action == "DeleteTask")
            {
                var taskD = await _dbContext.Tasks.FindAsync(editTask.Id);
                if (taskD != null)
                {
                    await _taskService.DeleteTaskAsync(taskD.Id);
                }
            }
            return RedirectToPage("Index");
        }
    }
}

TaskMenagerV2/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TaskMenager.Components.dbcontroll;


namespace TaskMenagerV2.Pages
{
    public class IndexModel : PageModel
    {
        private readonly MyDbContext _dbContext;


        public IndexModel(MyDbContext dbContext)
        {
            _dbContext = dbContext;
            editTask = new Tasks();
        }

        [BindProperty]
        public Tasks editTask { get; set; }

        public async Task<IActionResult> OnPostUpdateCompletion(int taskId)
        {
            var task = await _dbContext.Tasks.FindAsync(taskId);
            if (task != null)
            {
                task.Completion = task.Completion == 0 ? 1 : 0;
                await _dbContext.SaveChangesAsync();
            }

            return RedirectToPage("Index");
        }


        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("UserId") == null)
            {
                return RedirectToPage("/Login");
            }
            else
            {
                Console.WriteLine($"Logged in {HttpContext.Session.GetString("UserId")}");
                return Page();
            }
        }

    }
}

TaskMenagerV2/Pages/RestorePassword.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TaskMenagerV2.Pages.dbcontroll;
using TaskMenagerV2.Pages.Services;

namespace TaskMenagerV2.Pages
{
    public class RestorePasswordModel : PageModel
    {
        private readonly EmailService _emailService;
        private readonly IUserService _userService;
        private readonly MyDbContext _dbContext;

        public RestorePasswordModel(IUserService userService, MyDbContext dbContext, EmailService emailService)
        {
            _userService = userService;
            _dbContext = dbContext;
            _emailService = emailService;
        }

        [BindProperty]
        public User UserC { get; set; }

        [HttpPost]
        public async Task<IActionResult> OnPostSendEmailAsync(string Email)
        {
            var confirmationNumber = new Random().Next(1000, 9999);
            HttpContext.Session.SetInt32("ConfirmationNumber", confirmationNumber);

            await _emailService.SendEmailAsync(Email, "Confirmation", $"Your confirmation number is {confirmationNumber}.");

            return Page();
        }

        [HttpPost]
        public async Task<IActionResult> OnPostUpdatePasswordAsync(int userId, string Email, int Conf)
        {
            var savedConfirmationNumber = HttpContext.Session.GetInt32("ConfirmationNumber");
            if (Conf != savedConfirmationNumber)
            {
                return Page();
            }

            var users = await _userService.GetUsersByEmailAsync(Email);
            var user = users.FirstOrDefault();
            user.Password = UserC.Password;
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("/Account");
        }

    }
}

TaskMenagerV2/Pages/Account.cshtml
@page
@model TaskMenagerV2.Pages.AccountModel
@inject MyDbContext DbContext
@using TaskMenager.Components.dbcontroll;
@using Microsoft.EntityFrameworkCore;
@using TaskMenagerV2.Pages.Services
@using TaskMenagerV2.Pages.dbcontroll;
@{
    ViewData["Title"] = "Account";
    var user = ViewData["User"] as User;
    var achievementsString = user?.Achivements;
    var achievementsList = achievementsString?.Split(',').Select(int.Parse).ToList() ?? new List<int>();
}

<div class="container">
    <div class="text-center tp-4">
        <h2 class="display-4">Welcome back!</h2>
        @if (HttpContext.Session.GetString("UserId") != null)
        {
@*             <p class="tp-2">@user.Name!</p>
            <p class="tp-2">Your email: @user.Email</p> *@

            <form method="post" asp-page-handler="Logout" class="pt-2 pb-3">
                <button type="submit" class="btn btn-danger">Logout</button>
            </form>
            <button onclick="toggleTasksVisibility()" class="btn btn-outline-secondary mt-2 pb-2 mb-3">Change Account data</button>
            <div id="ChangeData" style="display: none;" class="mb-4">
                <form method="post" asp-page-handler="UpdatePassword" class="pt-2 align-content-center d-flex justify-content-center w-100">
                    <div class="w-50 text-start">
                        <input type="hidden" name="userId" value="@user.UserId" />
                        <div class="form-group pb-3 w-100">
                            <label asp-for="UserC.Email"></label>
                            <input asp-for="UserC.Email" class="form-control" placeholder="@user.Email" />
                            <span asp-validation-for="UserC.Email" class="text-danger"></span>
                        </div>
                        <div class="form-group pb-3 w-100">
                            <label asp-for="UserC.Name"></label>
                            <input asp-for="UserC.Name" class="form-control input-dark" placeholder="@user.Name" />
                            <span asp-validation-for="UserC.Name" class="text-danger"></span>
                        </div>
                        <div class="form-group pb-3 w-100">
                            <label asp-for="UserC.Password"></label>
                            <input asp-for="UserC.Password" class="form-control" />
                            <span asp-validation-for="UserC.Password" class="text-danger"></span>
                        </div>
                        <button type="submit" class="btn btn-primary pt-2 mb-4">Change data</button>
                    </div>
                </form>
            </div>

            <div class="row justify-content-center pb-3">
                <div class="col-md-8">
                    <h2>Completed Achievements</h2>
                    <div class="row">
                        @for (int i = 0; i < achievementsList.Count; i++)
                        {
                            if (achievementsList[i] == 1)
                            {
                                var achievement = DbContext.Achievements.FirstOrDefault(a => a.Id == i + 1);
                                if (achievement != null)
                                {
                                    <div class="col-md-4 pt-2 pb-2">
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">@achievement.Name</h5>
                                                <p class="card-text">@achievement.Description</p>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                        }
                        @if (!achievementsList.Any(a => a == 1))
                        {
                            <div class="h4">No completed achievements.</div>
                        }
                    </div>

                    <h2 class="pt-3">Incompleted Achievements</h2>
                    <div class="row">
                        @for (int i = 0; i < achievementsList.Count; i++)
                        {
                            if (achievementsList[i] == 0)
                            {
                                var achievement = DbContext.Achievements.FirstOrDefault(a => a.Id == i + 1);
                                if (achievement != null)
                                {
                                    <div class="col-md-4 pt-2 pb-2">
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">@achievement.Name</h5>
                                                <p class="card-text">@achievement.Description</p>
                                                @switch (achievement.Id)
                                                {
                                                    case 4:
                                                        double completed = DbContext.Tasks.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))).Count(t => t.Completion == 1);
                                                        int PercentCompletion = Convert.ToInt32((completed / 10) * 100);
                                                        <div class="pt-2"><progress max="100" value="@PercentCompletion"></progress> @PercentCompletion%</div>
                                                        break;
                                                    case 5:
                                                        completed = DbContext.Tasks.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))).Count(t => t.Completion == 1);
                                                        PercentCompletion = Convert.ToInt32((completed / 50) * 100);
                                                        <div class="pt-2"><progress max="100" value="@PercentCompletion"></progress> @PercentCompletion%</div>
                                                        break;
                                                    case 6:
                                                        completed = DbContext.Tasks.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))).Count(t => t.Completion == 1);
                                                        PercentCompletion = Convert.ToInt32((completed / 100) * 100);
                                                        <div class="pt-2"><progress max="100" value="@PercentCompletion"></progress> @PercentCompletion%</div>
                                                        break;
                                                    case 9:
                                                        int completedProjects = DbContext.Projects.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))).Count(p => p.Tasks.All(t => t.Completion == 1));
                                                        PercentCompletion = Convert.ToInt32((completedProjects / 10) * 100);
                                                        <div class="pt-2"><progress max="100" value="@PercentCompletion"></progress> @PercentCompletion%</div>
                                                        break;
                                                    case 10:
                                                        completed = DbContext.Tasks.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))).Count(t => t.Completion == 1);
                                                        PercentCompletion = Convert.ToInt32((completed / 10) * 100);
                                                        <div class="pt-2"><progress max="100" value="@PercentCompletion"></progress> @PercentCompletion%</div>
                                                        break;
                                                }
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                        }
                    </div>
                </div>
            </div>

            <form id="deleteForm" method="post" class="mt-4 mb-4" asp-page-handler="DeleteAccount">
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete Account</button>
                <input type="hidden" name="userId" value="@user.UserId" />
            </form>

            <!-- Button trigger modal -->
            <!--<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Launch demo modal
            </button>-->

            <!-- Modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog bg-dark">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete your account? This action cannot be undone.
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary" onclick="confirmDelete()">Confirm</button>
                        </div>
                    </div>
                </div>
            </div>

        }
        else
        {
            <p>Please log in or register.</p>
            <a class="btn text-body-secondary" asp-area="" asp-page="/Login">Log in</a>
            <a class="btn text-body-secondary" asp-area="" asp-page="/Registration">Register</a>
        }
    </div>
</div>

@section Scripts {
    <script>
        function confirmDelete() {
            // if (confirm('Are you sure you want to delete your account? This action cannot be undone.')) {
            //     document.getElementById('deleteForm').submit();
            // }
            document.getElementById('deleteForm').submit();
        }

        function toggleTasksVisibility() {
            var tasksContainer = document.getElementById('ChangeData');
            if (tasksContainer.style.display === 'none') {
                tasksContainer.style.display = 'block';
            } else {
                tasksContainer.style.display = 'none';
            }
        }

        var myModal = document.getElementById('deleteModal')
        var myInput = document.getElementById('myInput')

        myModal.addEventListener('shown.bs.modal', function () {
            myInput.focus()
        })

    </script>
}

TaskMenagerV2/Pages/Login.cshtml
@page
@model TaskMenagerV2.Pages.LoginModel
@{
	ViewData["Title"] = "Log in";
}

<div class="container">
    <h2 class="display-4">Login</h2>
    <div class="mb-1 mt-2">Or create new account: <a class="text-body-secondary" asp-area="" asp-page="/Registration">Register</a> </div>
    <form method="post">
        <div class="form-group w-50 pt-3">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email"></span>
        </div>
        <div class="form-group w-50 pt-3 pb-3">
            <label asp-for="Password"></label>
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password"></span>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Login</button>
    </form>

    <a class="btn btn-danger mt-4" asp-page="/RestorePassword">Forgot your password?</a>

</div>

TaskMenagerV2/Pages/RestorePassword.cshtml
@page
@model TaskMenagerV2.Pages.RestorePasswordModel
@{
	ViewData["Title"] = "Restore Password";
}

<div class="container">
    <h2 class="pt-3">Change Password</h2>

    <form method="post" asp-page-handler="SendEmail" class="pt-2 align-content-center">
        <div class="form-group w-25">
            <label for="Email">Email</label>
            <input id="Email" name="Email" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary mt-2">Send conformation email</button>
    </form>

    <form method="post" asp-page-handler="UpdatePassword" class="pt-4 align-content-center">
        <div class="form-group w-25 pt-2">
            <label for="Email">Email</label>
            <input id="Email" name="Email" class="form-control" />
        </div>
        <div class="form-group w-25 pt-2">
            <label for="Conf">Confirmation code</label>
            <input id="Conf" name="Conf" class="form-control" />
        </div>
        <div class="form-group w-25 pt-2 pb-2">
            <label asp-for="UserC.Password"></label>
            <input asp-for="UserC.Password" class="form-control" />
            <span asp-validation-for="UserC.Password" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Change Password</button>
    </form>
</div>